### PR TITLE
Enhancements and fixes

### LINKED ISSUE #112: Disable view when no workspace is chosen
Whenever the user hits OntoGrapher without correct workspace IRI (typically any request not originating from Control panel), OntoGrapher should inform the user that the workspace must be chosen first (and possibly - not necessarily - link back to Control panel).

### LINKED ISSUE #136: Support altlabels
Some labels are really not very practical (e.g. "má citaci označení fragmentu znění právního aktu"). It would be practical to use altLabels ("má citaci") to be shown in the diagram.

### LINKED ISSUE #148: Exploding connections moves with relators
I've started with putting object into the canvas. Relators were shown atomaticaly. Then I've started "exploding" connections from objects to visualize properties. Properties are shown, but unfortunately, relators already present in the layout are moved.

### LINKED ISSUE #151: Linking "proměnný prvek" from Z-SGoV to a relator type fails
1) https://mission-control.netlify.app/workspaces/instance2045554666
2) Editovat vztahy
3) Add "proměnný prvek" from Z-SGoV to the diagram

image

4) Link from "kóduje prvek"

image

5) connecting to "proměnný prvek" results to the failure:

image

### LINKED ISSUE #154: Vocabulary in the read-only mode shown as editable vocabulary
I have this workspace https://mission-control.netlify.app/workspaces/instance2045554666 :

image

In OG, I see that Z-SGoV is editable:

image

And I can really edit Z-SGoV.

### LINKED ISSUE #155: Hidden relations reappear after opening the OG again
I have created two tabs in Sbírka OG. In the fist tab are ONLY relations between terms from Sbírka. The second tab shall contain ONLY mapping to upper level vocabularies. This thing is, that most of the terms mapped are objects. I want to see here only objects, so automatically created relations between them were hidden. Unfortunately, if I get back to the WS and open the tab, relations are back.

### LINKED ISSUE #156: Changes to the model and layout of the diagram were not stored
I have this diagram (OFN klasifikace) in https://ontographer.netlify.app/?workspace=https://slovník.gov.cz/datový/pracovní-prostor/pojem/metadatový-kontext/instance2045554666

image

When I switch to another diagram in the same workspace and then back, I got this:

image

Red points = break points which were removed in the first

Violet line = associatoin which was deleted

When I do the changes again (i.e. remove the colored things), the diagram seems correct. When I switch to another diagram and back, they are still here.

### LINKED ISSUE #157: Blank screen after creating a link
After connecting two untyped nodes, I get a blank screen. E.g. after connecting Položka and Proměnný prvek in 

https://ontographer.netlify.app/?workspace=https://slovn%C3%ADk.gov.cz/datov%C3%BD/pracovn%C3%AD-prostor/pojem/metadatov%C3%BD-kontext/instance-145753951

image

image

### LINKED ISSUE #158: Disallow creating terms with the same prefLabel
If a term already with the same prefLabel already exists in the vocabulary, do not allow to create it and show an error to the user.

### LINKED ISSUE #161: Panning the canvas is laggy
In a [comment on a different issue](https://github.com/opendata-mvcr/ontoGrapher/issues/160#issuecomment-734276308), @MichalMed complained that panning the canvas is laggy. The change, therefore, should be such that it speeds up this interaction.

### PR DESCRIPTION
**Pull request by bindetad**
I am opening a preview deploy to, among other things, smooth out the main issues before wider testing.
## Notes:
* I made effort to improve issues within #160. If anything happens, the faulty request is sent to the console.
* In the last PR, there were some faulty contexts that were created in graphDB. These don't affect usage or results, but please report them to me anyway.
* I think that #152 is finished as well, but since I don't have an accurate description of the problem, the issue won't be closed with this PR.
## Changes:
* Implemented feedback from testing transactions. Transactions should be faster and less intensive on the server.
* Interaction with the tool is disabled when loading.
* Ellipses and trapezoids are slightly smaller, and the link edges align.
### Bug fixes:
* Some of these issues were related or almost exactly the same, so I will group them together.
* Closes #157, closes #151.
* Closes #156, closes #155.
* Closes #154.
* Closes #148.
### Enhancements:
* Closes #158: A potential IRI/label conflict disallows concept creation in the new concept modal dialogue.
* Closes #161: Panning the canvas is faster.
* Closes #112: Starting without a workspace displays an error.
* Closes #136: Implementation of altLabels.
#### #136: altLabels
* Editing prefLabels is disabled.
* The detail panel contains an additional section for Alternative labels.
* For R/W concepts, these can be added/renamed/deleted.
* A "display name" among pref/altLabels can be selected for a concept with the 🏷️ button. 
* This choice persists through the workspace. It does not affect the vocabulary itself; it is ontoGrapher-specific information.
* The default display name is selected from available altLabels; if there are none, prefLabels are used, as before.
* I appreciate any feedback you have about this feature.
## Deploys on current workspaces: 
* [JaKl Obchodní rejstřík](https://deploy-preview-162--ontographer.netlify.app/?workspace=https://slovník.gov.cz/datový/pracovní-prostor/pojem/metadatový-kontext/instance201242184)
* [V-SGoV pro číselníky](https://deploy-preview-162--ontographer.netlify.app/?workspace=https://slovník.gov.cz/datový/pracovní-prostor/pojem/metadatový-kontext/instance-145753951)
* [GSGoV klasifikací a číselníků](https://deploy-preview-162--ontographer.netlify.app/?workspace=https://slovník.gov.cz/datový/pracovní-prostor/pojem/metadatový-kontext/instance2045554666)
* [Sbírka](https://deploy-preview-162--ontographer.netlify.app/?workspace=https://slovník.gov.cz/datový/pracovní-prostor/pojem/metadatový-kontext/instance1178651091)
* [mm-test](https://deploy-preview-162--ontographer.netlify.app/?workspace=https://slovník.gov.cz/datový/pracovní-prostor/pojem/metadatový-kontext/instance-2000996011)
* [Marie test](https://deploy-preview-162--ontographer.netlify.app/?workspace=https://slovník.gov.cz/datový/pracovní-prostor/pojem/metadatový-kontext/instance-530560086)
* [Datové fondy VS](https://deploy-preview-162--ontographer.netlify.app/?workspace=https://slovník.gov.cz/datový/pracovní-prostor/pojem/metadatový-kontext/instance-1153182747)
* [ontoGrapher test](https://deploy-preview-162--ontographer.netlify.app/?workspace=https://slovník.gov.cz/datový/pracovní-prostor/pojem/metadatový-kontext/instance1087289886)
* [ML test](https://deploy-preview-162--ontographer.netlify.app/?workspace=https://slovník.gov.cz/datový/pracovní-prostor/pojem/metadatový-kontext/instance-1101091271)
* [Karel TestX](https://deploy-preview-162--ontographer.netlify.app/?workspace=https://slovník.gov.cz/datový/pracovní-prostor/pojem/metadatový-kontext/instance1170301076)

### CODE REVIEW

File: src/function/FunctionDraw.ts [hunk 1]
```diff
@@ -0,0 +1,88 @@
...
+		cell.attr({line: {stroke: color}});
+	} else {
+		if (cell.id) {
+			drawGraphElement(cell as joint.dia.Element, ProjectSettings.selectedLanguage, ProjectSettings.representation)
+		}
+	}
+}
+
+export function unHighlightAll() {
+	for (let cell of graph.getCells()) {
```
Comment (psiotwo) [inline src/function/FunctionDraw.ts:74]: Why not to use streams?

File: src/function/FunctionGetVars.ts [hunk 2]
```diff
@@ -59,12 +59,67 @@ export function setSchemeColors(pool: string) {
...
+export function getUnderlyingFullConnections(link: joint.dia.Link): { src: string, tgt: string } | undefined {
+	let id = link.id;
+	let iri = ProjectLinks[id].iri;
+	if (!(iri in VocabularyElements)) return;
+	let sourceElem = link.getSourceCell()?.id;
+	let targetElem = link.getTargetCell()?.id;
+	if (sourceElem && targetElem) {
+		let preds = Object.keys(ProjectElements).filter(id => ProjectElements[id].iri === iri);
+		for (let pred of preds) {
+			let sourceLink = Object.keys(ProjectLinks).find(id =>
```
Comment (psiotwo) [inline src/function/FunctionGetVars.ts:101]: these repeated blocks of code seem to be extractable to some method

File: src/function/FunctionGraph.ts [hunk 3]
```diff
@@ -14,59 +13,11 @@ import {
...
-}
-
-export function getNewLink(type?: number, id?: string): joint.dia.Link {
-    let link = new joint.shapes.standard.Link({id: id});
-    if (type && type in LinkConfig) {
-        link = LinkConfig[type].newLink(id);
-    }
-    return link;
-}
+export var mvp1IRI = "https://slovník.gov.cz/základní/pojem/má-vztažený-prvek-1";
```
Comment (psiotwo) [inline src/function/FunctionGraph.ts:19]: vars are obsolete AFAIK, https://www.freecodecamp.org/news/var-let-and-const-whats-the-difference/

File: src/interface/SPARQLInterface.ts [hunk 4]
```diff
@@ -42,7 +43,7 @@ export async function fetchConcepts(
         "PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>",
```
Comment (psiotwo) [inline src/interface/SPARQLInterface.ts:43]: Consider refactoring to some text file with variables, or using some SPARQL builder https://www.npmjs.com/package/@atomgraph/sparql-builder

File: src/interface/SPARQLInterface.ts [hunk 5]
```diff
@@ -84,14 +87,30 @@ export async function fetchConcepts(
                 }
             }
             if (row.termType && !(result[row.term.value].types.includes(row.termType.value))) result[row.term.value].types.push(row.termType.value);
-            if (row.termLabel) result[row.term.value].labels[row.termLabel['xml:lang']] = row.termLabel.value;
-            if (row.termDefinition) result[row.term.value].definitions[row.termDefinition['xml:lang']] = row.termDefinition.value;
+            if (row.termLabel) {
+                if (!(row.termLabel['xml:lang'] in result[row.term.value].labels))
+                    result[row.term.value].labels[row.termLabel['xml:lang']] = "";
```
Comment (psiotwo) [inline src/interface/SPARQLInterface.ts:92]: this deserves some variable declaration to avoid repeated code.

File: src/panels/detail/components/AltLabelTable.tsx [hunk 6]
```diff
@@ -0,0 +1,113 @@
...
+	onEdit: Function;
+	selectAsDefault: Function;
+	addAltLabel: Function;
+}
+
+interface State {
+	newAltInput: string;
+}
+
+export default class AltLabelTable extends React.Component<Props, State> {
```
Comment (psiotwo) [inline src/panels/detail/components/AltLabelTable.tsx:23]: This component seems quite huge, consider splitting into multiple smaller bits.

**Review by psiotwo — APPROVED** [review]
lgtm, see comments

**Comment by bindetad** [comment]
Thank you for the comments.

File: src/function/FunctionCreateVars.ts [hunk 7]
```diff
@@ -41,17 +42,9 @@ export function createValues(values: { [key: string]: string[] }, prefixes: { [k
...
-    if (result in target) {
-        while ((result + "-" + count.toString(10)) in target) {
-            count++;
-        }
-        result += "-" + count.toString(10);
-    }
-    return result;
+export function createNewElemIRI(scheme: string, name: string): string {
+    return (scheme.substring(0, scheme.lastIndexOf("/") + 1) + "pojem/" + name)
+        .trim().replace(/\s/g, '-').toLowerCase();
```
[the remark this answers is not in the document]
Comment (MichalMed) [reply src/function/FunctionCreateVars.ts:47]: that seems weird
