### PR TITLE
[#239] "Self loop" issue

### LINKED ISSUE #239: Wrongly created specialization of a class by itself
A specialization of a class by itself has appeared in my model. I do not know how it appeared in the model but:

1) Ontographer should not allow the user to create such specialization.

2) If there is such specialization in the model, I need to be able to remove it. However, this is not possible in the current way of visualization in the diagram:

image

You can try this on https://slovník.gov.cz/legislativní/sbírka/90/2012/pojem/družstvo

### PR DESCRIPTION
**Pull request by bindeali**
## Info:
* Closes #239.
* Can be merged and closed right away.
## Detailed changes:
* Disallowed creation of generalizations with the same target and source term.
* Fixed an issue where the "loop" for relationships with the same target and source term was not created, which prevented selection (and deletion) of the relationship.
## Deploy previews: 
* [ML test](https://deploy-preview-249--ontographer.netlify.app/?workspace=https://slovn%C3%ADk.gov.cz/datov%C3%BD/pracovn%C3%AD-prostor/pojem/metadatov%C3%BD-kontext/instance-1101091271)
* [Datové fondy VS](https://deploy-preview-249--ontographer.netlify.app/?workspace=https://slovn%C3%ADk.gov.cz/datov%C3%BD/pracovn%C3%AD-prostor/pojem/metadatov%C3%BD-kontext/instance-1153182747)
* [Marie test](https://deploy-preview-249--ontographer.netlify.app/?workspace=https://slovn%C3%ADk.gov.cz/datov%C3%BD/pracovn%C3%AD-prostor/pojem/metadatov%C3%BD-kontext/instance-530560086)
* [mm-test](https://deploy-preview-249--ontographer.netlify.app/?workspace=https://slovn%C3%ADk.gov.cz/datov%C3%BD/pracovn%C3%AD-prostor/pojem/metadatov%C3%BD-kontext/instance-2000996011)
* [Sčítání lidu](https://deploy-preview-249--ontographer.netlify.app/?workspace=https://slovn%C3%ADk.gov.cz/datov%C3%BD/pracovn%C3%AD-prostor/pojem/metadatov%C3%BD-kontext/instance-2011762727)
* [Sbírka](https://deploy-preview-249--ontographer.netlify.app/?workspace=https://slovn%C3%ADk.gov.cz/datov%C3%BD/pracovn%C3%AD-prostor/pojem/metadatov%C3%BD-kontext/instance1483547911)
* [Právnické a fyzické osoby v rejstřících](https://deploy-preview-249--ontographer.netlify.app/?workspace=https://slovn%C3%ADk.gov.cz/datov%C3%BD/pracovn%C3%AD-prostor/pojem/metadatov%C3%BD-kontext/instance-1872291546)
* [Správný model konkrétního číselníku](https://deploy-preview-249--ontographer.netlify.app/?workspace=https://slovn%C3%ADk.gov.cz/datov%C3%BD/pracovn%C3%AD-prostor/pojem/metadatov%C3%BD-kontext/instance570218201)
* [čas](https://deploy-preview-249--ontographer.netlify.app/?workspace=https://slovn%C3%ADk.gov.cz/datov%C3%BD/pracovn%C3%AD-prostor/pojem/metadatov%C3%BD-kontext/instance-1474929552)
* [Karel Test](https://deploy-preview-249--ontographer.netlify.app/?workspace=https://slovn%C3%ADk.gov.cz/datov%C3%BD/pracovn%C3%AD-prostor/pojem/metadatov%C3%BD-kontext/instance-1231949029)
* [Školení - doména řidičů a vozidel](https://deploy-preview-249--ontographer.netlify.app/?workspace=https://slovn%C3%ADk.gov.cz/datov%C3%BD/pracovn%C3%AD-prostor/pojem/metadatov%C3%BD-kontext/instance-946737236)
* [Školení - doména poslanecké sněmovny](https://deploy-preview-249--ontographer.netlify.app/?workspace=https://slovn%C3%ADk.gov.cz/datov%C3%BD/pracovn%C3%AD-prostor/pojem/metadatov%C3%BD-kontext/instance1938652144)
* [Školení - doména registru práv a povinností](https://deploy-preview-249--ontographer.netlify.app/?workspace=https://slovn%C3%ADk.gov.cz/datov%C3%BD/pracovn%C3%AD-prostor/pojem/metadatov%C3%BD-kontext/instance-510905468)
* [Školení - ukázka veřejné zakázky](https://deploy-preview-249--ontographer.netlify.app/?workspace=https://slovn%C3%ADk.gov.cz/datov%C3%BD/pracovn%C3%AD-prostor/pojem/metadatov%C3%BD-kontext/instance-936554450)
* [Školení - veřejné zakázky](https://deploy-preview-249--ontographer.netlify.app/?workspace=https://slovn%C3%ADk.gov.cz/datov%C3%BD/pracovn%C3%AD-prostor/pojem/metadatov%C3%BD-kontext/instance1008211408)
* [Testovací WS pro formální jazyky](https://deploy-preview-249--ontographer.netlify.app/?workspace=https://slovn%C3%ADk.gov.cz/datov%C3%BD/pracovn%C3%AD-prostor/pojem/metadatov%C3%BD-kontext/instance-2039280178)

### CODE REVIEW

File: src/function/FunctionGraph.ts [hunk 1]
```diff
@@ -232,6 +232,29 @@ export function setRepresentation(representation: number): { result: boolean, tr
     }
 }
 
+export function checkLinkSelfLoop(link: joint.dia.Link) {
```
Comment (karelklima) [inline src/function/FunctionGraph.ts:235]: Two minor things here, up to you if you modify the code:
1) The function probably does not need to be exported since it's only use seems to be in this file.
2) I'd consider a different name. It's weird to have something named "check..." and then return an array of points.

**Review by karelklima — APPROVED** [review]
