### PR TITLE
#277 fix

### LINKED ISSUE #277: Compact view shows duplicate items
Tested on prod, ws: eSbírka a CzechVoc

Compact view shows the class Právní akt as follows:
image

Attributes (e.g. "účinnost od") appears twice in the list. I tried to check the result of 
`PREFIX d-sgov-pracovní-prostor-pojem-slovníkový-kontext: <https://slovník.gov.cz/datový/pracovní-prostor/pojem/slovníkový-kontext/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
select * where { 
    GRAPH d-sgov-pracovní-prostor-pojem-slovníkový-kontext:instance2124069728 {
		<https://slovník.gov.cz/datový/sbírka/pojem/právní-akt> rdfs:subClassOf _:c .
        _:c owl:allValuesFrom ?o .
    }
}` - it gives the list with props unique.

### PR DESCRIPTION
**Pull request by bindeali**
## Info:
* Closes #277.
* Can be merged and closed right away.

### CODE REVIEW

File: src/function/FunctionDraw.ts [hunk 1]
```diff
@@ -79,7 +80,7 @@ export function drawGraphElement(
           )
         );
     }
-    elem.prop("attrs/labelAttrs/text", text.join("\n"));
+    elem.prop("attrs/labelAttrs/text", _.uniq(text).join("\n"));
```
Comment (psiotwo) [inline src/function/FunctionDraw.ts:83]: lgtm, 

yet what is the reason that text contains duplicates?

**Review by psiotwo — APPROVED** [review]
