### PR TITLE
#278 fix

### LINKED ISSUE #278: Blank screen after trying a loop edge in compact mode.
tested on dev, workspace "eSbírka v AJ"

after switching the diagram
image

to compact mode I get
image

Whenever I try to move a loop edge, I get a blank screen:
image

### PR DESCRIPTION
**Pull request by bindeali**
## Info:
* Closes #278.
* Can be merged and closed right away.

### CODE REVIEW

File: src/panels/detail/DetailLink.tsx [hunk 1]
```diff
@@ -174,30 +174,26 @@ export default class DetailLink extends React.Component<Props, State> {
...
-              targetCard.getFirstCardinality()
-            );
-            WorkspaceLinks[
-              underlyingConnections.tgt
-            ].targetCardinality = new Cardinality(
-              targetCard.getSecondCardinality(),
-              targetCard.getSecondCardinality()
-            );
+            WorkspaceLinks[underlyingConnections.src].sourceCardinality =
+              new Cardinality(
```
Comment (psiotwo) [inline src/panels/detail/DetailLink.tsx:178]: why not to extract cardinality construction to a separate method?

**Review by psiotwo — APPROVED** [review]
lgtm, see comment
