### PR TITLE
Interface language change implementation

### LINKED ISSUE #331: UI language changing support
### Current status
The language is changed based on the language of the browser (navigator.language).

### Issues

- The language cannot be changed at runtime.
- The language is dependent on the user language, which must be changed by going into the browser/OS settings. The user, therefore, cannot be set for OG only.
- For some people, this doesn't work at all (it is undesirably dependent on the users' personal configuration).

### Solution proposals
These can be used either on their own or in combination.

- The language is pulled from Keycloak.
- The language can be set in the UI (for example, in the View submenu on the Menu bar)
- The language is persisted per workspace (easily implemented) or per user (also easy, but requires intrusion into the user context or a new OG-specific context).

Request for comment @opendata-mvcr/c5-frontend-reviewers @MichalMed

### PR DESCRIPTION
**Pull request by bindeali**
## Info:
* Closes #331: Implemented setting to change the language of the user interface.
* Changes are persisted via LocalStorage.
* Moved workspace language change setting to the View submenu:
image

### CODE REVIEW

File: src/locale/en.ts [hunk 1]
```diff
@@ -25,6 +25,8 @@ export const en = {
   detailPanelInScheme: "In vocabulary",
   detailPanelDefinition: "Definition",
   detailPanelStereotype: "Stereotype",
+  setCanvasLanguage: "Workspace language",
```
Comment (bindeali) [inline src/locale/en.ts:28]: Do you think these names for the individual settings are OK? I thought about it a bit but haven't been able to come up with better ones.

File: src/locale/cs.ts [hunk 2]
```diff
@@ -32,6 +32,8 @@ export const cs: { [Property in keyof typeof en]: string } = {
   detailPanelInScheme: "Ve slovníku",
   detailPanelDefinition: "Definice",
   detailPanelStereotype: "Stereotyp",
+  setCanvasLanguage: "Jazyk pracovního prostoru",
+  setInterfaceLanguage: "Jazyk uživatelského rozhraní",
```
Comment (bindeali) [inline src/locale/cs.ts:36]: Same comment as the previous one, but with Czech names.

File: src/locale/en.ts (hunk 1 above)
Comment (karelklima) [reply src/locale/en.ts:28]: What about "Default vocabulary language" or "Displayed vocabulary language"?

File: src/panels/menu/view/MenuPanelChangeLanguage.tsx [hunk 3]
```diff
@@ -0,0 +1,35 @@
+import * as React from "react";
+import { Dropdown } from "react-bootstrap";
+import { Locale } from "../../../config/Locale";
+import { AppSettings, Languages } from "../../../config/Variables";
+import { en } from "../../../locale/en";
+
+interface Props {
+  handleChangeLanguage: (language: string) => void;
+  title: keyof typeof en;
+  language: "interfaceLanguage" | "canvasLanguage";
```
Comment (karelklima) [inline src/panels/menu/view/MenuPanelChangeLanguage.tsx:10]: I suggest renaming this to `languageType` or something similar.

**Review by karelklima — DISMISSED** [review]

File: src/main/App.tsx [hunk 4]
```diff
@@ -137,25 +138,32 @@ export default class App extends React.Component<
...
       this.handleStatus(
         false,
-        Locale[AppSettings.viewLanguage].pleaseReload,
+        Locale[AppSettings.interfaceLanguage].pleaseReload,
         true
       );
     }
   }
 
+  handleChangeInterfaceLanguage(languageCode: string) {
```
[the remark this answers is not in the document]
Comment (bindeali) [reply src/main/App.tsx:151]: Yes, I believe we have had such a conversation before. I agree; I found this especially frustrating at the time of adding many features to various panels (such as this) and considered adding Redux to fix it. The problem is that there is always another more important bug or feature... I'll look into ways of introducing Redux gradually.

**Comment by bindeali** [comment]
Implemented suggestions in d914e6a.

File: src/main/App.tsx (hunk 4 above)
[the remark this answers is not in the document]
Comment (karelklima) [reply src/main/App.tsx:152]: Maybe it would be worth looking into this project - it's a simple Redux alternative that can be adopted gradually easily. https://github.com/lostpebble/pullstate

**Review by karelklima — APPROVED** [review]
Looks great :-)
